name: EUCLight Main CI

on: [push, pull_request]

jobs:
  buildMain:
    name: Compile main project
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Install Homebrew
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
        
      - name: Install Arduino CLI
        run: brew install arduino-cli

      - name: Install Arduino Uno core
        run: arduino-cli core install arduino:avr:uno

      - name: Install FastLED library
        run: arduino-cli lib install FastLED
        
      - name: Compile sketch
        run: arduino-cli compile -b arduino:avr:uno euclight --dry-run
